Home/urls.py
from django.urls import path

from . import views
app_name = 'quiz'

urlpatterns = [
    path('',views.Home,name='home'),
    path('python/',views.Python_Quiz,name='python'),
    path('django/',views.Django_Quiz,name='django'),
    path('angular/',views.Angular_Quiz,name='angular'),
    path('php/',views.PHP_Quiz,name='php'),
    path('java/',views.Java_Quiz,name='java'),
    path('javascript/',views.JavaScript_Quiz,name='javascript'),
    path('dot_net/',views.Dot_Net_Quiz,name='dot_net'),
    path('react/',views.React_Quiz,name='react'),
    path('nodejs/',views.Node_Js_Quiz,name='nodejs'),
]

Quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('user/',include('user.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views
app_name = 'user'

urlpatterns = [
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout,name='logout'),
]

Home/models.py
from django.db import models


# Create your models here.
class Python(models.Model):
    question = models.CharField(max_length=200, null=True)
    opt1 = models.CharField(max_length=200, null=True)
    opt2 = models.CharField(max_length=200, null=True)
    opt3 = models.CharField(max_length=200, null=True)
    opt4 = models.CharField(max_length=200, null=True)
    ans = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.question


class Django(models.Model):
    question = models.CharField(max_length=200, null=True)
    opt1 = models.CharField(max_length=200, null=True)
    opt2 = models.CharField(max_length=200, null=True)
    opt3 = models.CharField(max_length=200, null=True)
    opt4 = models.CharField(max_length=200, null=True)
    ans = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.question


class Angular(models.Model):
    question = models.CharField(max_length=200, null=True)
    opt1 = models.CharField(max_length=200, null=True)
    opt2 = models.CharField(max_length=200, null=True)
    opt3 = models.CharField(max_length=200, null=True)
    opt4 = models.CharField(max_length=200, null=True)
    ans = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.question


class React(models.Model):
    question = models.CharField(max_length=200, null=True)
    opt1 = models.CharField(max_length=200, null=True)
    opt2 = models.CharField(max_length=200, null=True)
    opt3 = models.CharField(max_length=200, null=True)
    opt4 = models.CharField(max_length=200, null=True)
    ans = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.question


class JavaScript(models.Model):
    question = models.CharField(max_length=200, null=True)
    opt1 = models.CharField(max_length=200, null=True)
    opt2 = models.CharField(max_length=200, null=True)
    opt3 = models.CharField(max_length=200, null=True)
    opt4 = models.CharField(max_length=200, null=True)
    ans = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.question


class Java(models.Model):
    question = models.CharField(max_length=200, null=True)
    opt1 = models.CharField(max_length=200, null=True)
    opt2 = models.CharField(max_length=200, null=True)
    opt3 = models.CharField(max_length=200, null=True)
    opt4 = models.CharField(max_length=200, null=True)
    ans = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.question


class PHP(models.Model):
    question = models.CharField(max_length=200, null=True)
    opt1 = models.CharField(max_length=200, null=True)
    opt2 = models.CharField(max_length=200, null=True)
    opt3 = models.CharField(max_length=200, null=True)
    opt4 = models.CharField(max_length=200, null=True)
    ans = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.question


class Dot_Net(models.Model):
    question = models.CharField(max_length=200, null=True)
    opt1 = models.CharField(max_length=200, null=True)
    opt2 = models.CharField(max_length=200, null=True)
    opt3 = models.CharField(max_length=200, null=True)
    opt4 = models.CharField(max_length=200, null=True)
    ans = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.question


class Node_JS(models.Model):
    question = models.CharField(max_length=200, null=True)
    opt1 = models.CharField(max_length=200, null=True)
    opt2 = models.CharField(max_length=200, null=True)
    opt3 = models.CharField(max_length=200, null=True)
    opt4 = models.CharField(max_length=200, null=True)
    ans = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.question

Home/views.py
from django.shortcuts import render
from .models import PHP, Python, JavaScript, Angular, Java, React, Django, Dot_Net, Node_JS


# Create your views here.
def Home(request):
    return render(request, 'Home.html')


def Python_Quiz(request):
    if request.method == 'POST':
        questions = Python.objects.all()
        wrong = 0
        correct = 0
        total = 0
        for question in questions:
            total = total + 1
            selected_answer = request.POST.get('selected_answers_{}'.format(question.id))
            if selected_answer == question.ans:
                correct = correct + 1
            else:
                wrong = wrong + 1
        score = correct / len(questions) * 100
        percentage = score / (total * 10) * 100
        context = {
            'score': score,
            'correct': correct,
            'wrong': wrong,
            'total': total,
            'percentage': percentage
        }
        return render(request, 'Python_Result.html', context)

    questions = Python.objects.all()
    context = {'questions': questions}
    return render(request, 'Python.html', context)


def Django_Quiz(request):
    if request.method == 'POST':
        questions = Django.objects.all()
        correct = 0
        wrong = 0
        total = 0
        for question in questions:
            total = total + 1
            selected_answers = request.POST.get('selected_answers_{}'.format(question.id))
            if selected_answers == question.ans:
                correct = correct + 1
            else:
                wrong = wrong + 1
        score = correct / len(questions) * 100
        percentage = score / (total * 10) * 100
        context = {'score': score,
                   'percentage': percentage,
                   'correct': correct,
                   'wrong': wrong,
                   'total': total}
        return render(request, 'Django_Result.html', context)
    questions = Django.objects.all()
    context = {
        'questions': questions}
    return render(request, 'Django.html', context)


def Angular_Quiz(request):
    if request.method == 'POST':
        questions = Angular.objects.all()
        correct = 0
        wrong =0
        total =0
        for question in questions:
            total = total+1
            selected_answers = request.POST.get('selected_answers_{}'.format(question.id))
            if selected_answers == question.ans:
                correct = correct+1
            else:
                wrong = wrong+1
        score = correct / len(questions)*100
        percentage = score/(total*10)*100
        context = {'score':score,
                   'percentage':percentage,
                   'correct':correct,
                   'wrong':wrong,
                   'total':total}
        return render(request,'Angular_Result.html',context)
    angular = Angular.objects.all()
    context = {'angular': angular}
    return render(request, 'Angular.html', context)


def PHP_Quiz(request):
    if request.method == 'POST':
        questions = PHP.objects.all()
        correct = 0
        wrong =0
        total =0
        for question in questions:
            total = total+1
            selected_answers = request.POST.get('selected_answers_{}'.format(question.id))
            if selected_answers == question.ans:
                correct = correct+1
            else:
                wrong = wrong+1
        score = correct / len(questions)*100
        percentage = score/(total*10)*100
        context = {'score':score,
                   'percentage':percentage,
                   'correct':correct,
                   'wrong':wrong,
                   'total':total}
        return render(request,'PHP_Result.html',context)
    php = PHP.objects.all()
    context = {
        'php': php
    }
    return render(request, 'PHP.html', context)


def Java_Quiz(request):
    if request.method == 'POST':
        questions = Java.objects.all()
        correct = 0
        wrong =0
        total =0
        for question in questions:
            total = total+1
            selected_answers = request.POST.get('selected_answers_{}'.format(question.id))
            if selected_answers == question.ans:
                correct = correct+1
            else:
                wrong = wrong+1
        score = correct / len(questions)*100
        percentage = score/(total*10)*100
        context = {'score':score,
                   'percentage':percentage,
                   'correct':correct,
                   'wrong':wrong,
                   'total':total}
        return render(request,'Java_Result.html',context)
    java = Java.objects.all()
    context = {
        'java': java
    }
    return render(request, 'Java.html', context)


def JavaScript_Quiz(request):
    if request.method == 'POST':
        questions = JavaScript.objects.all()
        correct = 0
        wrong =0
        total =0
        for question in questions:
            total = total+1
            selected_answers = request.POST.get('selected_answers_{}'.format(question.id))
            if selected_answers == question.ans:
                correct = correct+1
            else:
                wrong = wrong+1
        score = correct / len(questions)*100
        percentage = score/(total*10)*100
        context = {'score':score,
                   'percentage':percentage,
                   'correct':correct,
                   'wrong':wrong,
                   'total':total}
        return render(request,'JavaScript_Result.html',context)
    javascript = JavaScript.objects.all()
    context = {
        'javascript': javascript
    }
    return render(request, 'JavaScript.html', context)


def Dot_Net_Quiz(request):
    if request.method == 'POST':
        questions = Dot_Net.objects.all()
        correct = 0
        wrong =0
        total =0
        for question in questions:
            total = total+1
            selected_answers = request.POST.get('selected_answers_{}'.format(question.id))
            if selected_answers == question.ans:
                correct = correct+1
            else:
                wrong = wrong+1
        score = correct / len(questions)*100
        percentage = score/(total*10)*100
        context = {'score':score,
                   'percentage':percentage,
                   'correct':correct,
                   'wrong':wrong,
                   'total':total}
        return render(request,'Dot_Net_Result.html',context)
    dot_net = Dot_Net.objects.all()
    context = {
        'dot_net': dot_net
    }
    return render(request, 'Dot_Net.html', context)


def React_Quiz(request):
    if request.method == 'POST':
        questions = React.objects.all()
        correct = 0
        wrong =0
        total =0
        for question in questions:
            total = total+1
            selected_answers = request.POST.get('selected_answers_{}'.format(question.id))
            if selected_answers == question.ans:
                correct = correct+1
            else:
                wrong = wrong+1
        score = correct / len(questions)*100
        percentage = score/(total*10)*100
        context = {'score':score,
                   'percentage':percentage,
                   'correct':correct,
                   'wrong':wrong,
                   'total':total}
        return render(request,'React_Result.html',context)
    react = React.objects.all()
    context = {
        'react': react
    }
    return render(request, 'React.html', context)


def Node_Js_Quiz(request):
    if request.method == 'POST':
        questions = Node_JS.objects.all()
        correct = 0
        wrong =0
        total =0
        for question in questions:
            total = total+1
            selected_answers = request.POST.get('selected_answers_{}'.format(question.id))
            if selected_answers == question.ans:
                correct = correct+1
            else:
                wrong = wrong+1
        score = correct / len(questions)*100
        percentage = score/(total*10)*100
        context = {'score':score,
                   'percentage':percentage,
                   'correct':correct,
                   'wrong':wrong,
                   'total':total}
        return render(request,'NodeJs_Result.html',context)
    nodejs = Node_JS.objects.all()
    context = {
        'nodejs': nodejs
    }
    return render(request, 'Node_JS.html', context)

templates/Angular.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-sm-12">
        <form action="{% url 'quiz:angular' %}" method="post">
        {% csrf_token %}
        {% for a in angular %}
        <h4>{{a.question}}</h4>
        <select name="selected_answers_{{ a.id }}" style="width:300px;">
            <option value="option">--Select Answer--</option><br>
            <option value="{{a.opt1}}">{{a.opt1}}</option><br>
            <option value="{{a.opt2}}">{{a.opt2}}</option><br>
            <option value="{{a.opt3}}">{{a.opt3}}</option><br>
            <option value="{{a.opt4}}">{{a.opt4}}</option><br>
        </select>
            <br>
            <br>
        {% endfor %}
        <button class="btn btn-success" type="submit">Submit</button> <button class="btn btn-warning" type="reset">Reset</button>
        </form>
    </div>
</div>
{% endblock %}

templates/Java.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-sm-12">
        <form action="{% url 'quiz:java' %}" method="post">
            {% csrf_token %}
            {% for j in java %}
            <h4>{{j.question}}</h4>
            <select name="selected_answers_{{ j.id }}" style="width:300px;">
                <option value="option">--Select Answer--</option><br>
                <option value="{{j.opt1}}">{{j.opt1}}</option><br>
                <option value="{{j.opt2}}">{{j.opt2}}</option><br>
                <option value="{{j.opt3}}">{{j.opt3}}</option><br>
                <option value="{{j.opt4}}">{{j.opt4}}</option><br>
            </select>
            <br>
            <br>
            {% endfor %}
        <button class="btn btn-success" type="submit">Submit</button> <button class="btn btn-warning" type="reset">Reset</button>
        </form>
    </div>
</div>
{% endblock %}

templates/JavaScript.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-sm-12">
        <form action="{% url 'quiz:javascript' %}" method="post">
            {% csrf_token %}
            {% for js in javascript %}
            <h4>{{js.question}}</h4>
            <select name="selected_answers_{{ js.id }}" style="width:300px;">
                <option value="option">--Select Answer--</option><br>
                <option value="{{js.opt1}}">{{js.opt1}}</option><br>
                <option value="{{js.opt2}}">{{js.opt2}}</option><br>
                <option value="{{js.opt3}}">{{js.opt3}}</option><br>
                <option value="{{js.opt4}}">{{js.opt4}}</option><br>
            </select>
            <br>
            <br>
            {% endfor %}
        <button class="btn btn-success" type="submit">Submit</button> <button class="btn btn-warning" type="reset">Reset</button>
        </form>
    </div>
</div>
{% endblock %}

templates/JavaScript_Result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Python Result
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 col-sm-12">
      <center><img src="{% static 'images/result.png' %}"></center>
      <div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="background-image:url('{% static 'images/resultbg.jpg' %}')">
        <h5 class="card-title" style="color:blue">Score : {{score}}</h5>
          <p class="card-text" style="color:blue">Percentage : {{percentage}}%</p>
          <p class="card-text" style="color:green">Correct answers : {{correct}}</p>
          <p class="card-text" style="color:red">Incorrect answers : {{wrong}}</p>
          <p class="card-text" style="color:blue">total : {{total}}</p>
          <p class="card-text" style="color:green"><small class="text">All the best for next quiz!</small></p>
      </div>
    </div>
  </div>
<br>
<br>
<br>
<br>

{% endblock %}

templates/Java_Result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Python Result
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 col-sm-12">
      <center><img src="{% static 'images/result.png' %}"></center>
      <div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="background-image:url('{% static 'images/resultbg.jpg' %}')">
        <h5 class="card-title" style="color:blue">Score : {{score}}</h5>
          <p class="card-text" style="color:blue">Percentage : {{percentage}}%</p>
          <p class="card-text" style="color:green">Correct answers : {{correct}}</p>
          <p class="card-text" style="color:red">Incorrect answers : {{wrong}}</p>
          <p class="card-text" style="color:blue">total : {{total}}</p>
          <p class="card-text" style="color:green"><small class="text">All the best for next quiz!</small></p>
      </div>
    </div>
  </div>
<br>
<br>
<br>
<br>

{% endblock %}

templates/NodeJs_Result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Python Result
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 col-sm-12">
      <center><img src="{% static 'images/result.png' %}"></center>
      <div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="background-image:url('{% static 'images/resultbg.jpg' %}')">
        <h5 class="card-title" style="color:blue">Score : {{score}}</h5>
          <p class="card-text" style="color:blue">Percentage : {{percentage}}%</p>
          <p class="card-text" style="color:green">Correct answers : {{correct}}</p>
          <p class="card-text" style="color:red">Incorrect answers : {{wrong}}</p>
          <p class="card-text" style="color:blue">total : {{total}}</p>
          <p class="card-text" style="color:green"><small class="text">All the best for next quiz!</small></p>
      </div>
    </div>
  </div>
<br>
<br>
<br>
<br>

{% endblock %}

templates/PHP.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-sm-12">
        <form action="{% url 'quiz:php' %}" method="post">
            {% csrf_token %}
            {% for p in php %}
            <h4>{{p.question}}</h4>
            <select name="selected_answers_{{ p.id }}" style="width:300px;">
                <option value="option">--Select Answer--</option><br>
                <option value="{{p.opt1}}">{{p.opt1}}</option><br>
                <option value="{{p.opt2}}">{{p.opt2}}</option><br>
                <option value="{{p.opt3}}">{{p.opt3}}</option><br>
                <option value="{{p.opt4}}">{{p.opt4}}</option><br>
            </select>
            <br>
            <br>
            {% endfor %}
        <button class="btn btn-success" type="submit">Submit</button> <button class="btn btn-warning" type="reset">Reset</button>
        </form>
    </div>
</div>
{% endblock %}

templates/PHP_Result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Python Result
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 col-sm-12">
      <center><img src="{% static 'images/result.png' %}"></center>
      <div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="background-image:url('{% static 'images/resultbg.jpg' %}')">
        <h5 class="card-title" style="color:blue">Score : {{score}}</h5>
          <p class="card-text" style="color:blue">Percentage : {{percentage}}%</p>
          <p class="card-text" style="color:green">Correct answers : {{correct}}</p>
          <p class="card-text" style="color:red">Incorrect answers : {{wrong}}</p>
          <p class="card-text" style="color:blue">total : {{total}}</p>
          <p class="card-text" style="color:green"><small class="text">All the best for next quiz!</small></p>
      </div>
    </div>
  </div>
<br>
<br>
<br>
<br>

{% endblock %}

templates/React.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-sm-12">
        <form action="{% url 'quiz:react' %}" method="post">
            {% csrf_token %}
            {% for r in react %}
            <h4>{{r.question}}</h4>
            <select name="selected_answers_{{ r.id }}" style="width:300px;">
                <option value="option">--Select Answer--</option><br>
                <option value="{{r.opt1}}">{{r.opt1}}</option><br>
                <option value="{{r.opt2}}">{{r.opt2}}</option><br>
                <option value="{{r.opt3}}">{{r.opt3}}</option><br>
                <option value="{{r.opt4}}">{{r.opt4}}</option><br>
            </select>
            <br>
            <br>
            {% endfor %}
        <button class="btn btn-success" type="submit">Submit</button> <button class="btn btn-warning" type="reset">Reset</button>
        </form>
    </div>
</div>
{% endblock %}

templates/React_Result.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Python Result
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-6 col-sm-12">
      <center><img src="{% static 'images/result.png' %}"></center>
      <div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="background-image:url('{% static 'images/resultbg.jpg' %}')">
        <h5 class="card-title" style="color:blue">Score : {{score}}</h5>
          <p class="card-text" style="color:blue">Percentage : {{percentage}}%</p>
          <p class="card-text" style="color:green">Correct answers : {{correct}}</p>
          <p class="card-text" style="color:red">Incorrect answers : {{wrong}}</p>
          <p class="card-text" style="color:blue">total : {{total}}</p>
          <p class="card-text" style="color:green"><small class="text">All the best for next quiz!</small></p>
      </div>
    </div>
  </div>
<br>
<br>
<br>
<br>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'style/register/register.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>

<!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!--  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>-->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,700,900" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'style/footer.css' %}">
  <title>{% block title %}{% endblock %}</title>
  <style>
    .base{
    background-image: url('{% static 'images/home_bg.jpg' %}');
    }
    .card-img-top {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 35%;
      height: 80%;
    }
  </style>
</head>
<body class="base">
<div class="container" style="font-family: cursive;">
{% include 'nav.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
  <div class="col-md-6 col-sm-12">
      <h2 class="card-title text-center" style="color:black;"><b>Login your Account</b></h2>
   <div class="card bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" style="width:100%; background-image:url('{% static 'images/login.jpeg' %}')">
      <div class="card-body py-md-4">
       <form action="{% url 'user:login' %}" method="post">
           {% csrf_token %}
          <div class="form-group">
              <input type="text" class="form-control" id="name" name="username" placeholder="User Name">
          </div>
           <div class="form-group">
               <input type="password" class="form-control" id="password" name="password" placeholder="Password">
           </div>
            <div>
                <center><button class="btn btn-success">Login</button></center>
            </div>
       </form>
          {% for msg in messages %}
          <div class="alert alert-warning" role="alert">
              {{msg}}
          </div>
          {% endfor %}
     </div>
  </div>
</div>
</div>
<br>
<br>
<br>
<br>
{% endblock %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="font-family: cursive;">
  <a class="navbar-brand" href="{% url 'quiz:home' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    {% if user.is_authenticated %}
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Take Quizzes
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'quiz:python' %}">Python</a>
          <a class="dropdown-item" href="{% url 'quiz:django' %}">Django</a>
          <a class="dropdown-item" href="{% url 'quiz:angular' %}">Angular</a>
          <a class="dropdown-item" href="{% url 'quiz:react' %}">React</a>
          <a class="dropdown-item" href="{% url 'quiz:java' %}">Java</a>
          <a class="dropdown-item" href="{% url 'quiz:javascript' %}">JavaScript</a>
          <a class="dropdown-item" href="{% url 'quiz:php' %}">PHP</a>
          <a class="dropdown-item" href="{% url 'quiz:nodejs' %}">Node Js</a>
          <a class="dropdown-item" href="{% url 'quiz:dot_net' %}"> Dot Net</a>
        </div>
      </li>
    </ul>
     <ul class="nav navbar-nav navbar-right">
       <li><a href="{% url 'user:logout' %}"><span style="color:red" class="glyphicon glyphicon-user">Logout</span></a></li>
     </ul>
       {% else %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'user:register' %}"><span style="color:blue" class="glyphicon glyphicon-user">Sign Up</span></a></li>
      <li><a href="{% url 'user:login' %}"><span style="color:green" class="glyphicon glyphicon-log-in"> Login</span></a></li>
       {% endif %}
    </ul>
  </div>
</nav>